import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signInWithRedirect, getRedirectResult, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { getFirestore, collection, doc, setDoc, addDoc, deleteDoc, onSnapshot, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js?v=1';
const OWNER_EMAIL='mh.makrostore@gmail.com';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});
const $=id=>document.getElementById(id);const r={loading:$('loading'),loginView:$('loginView'),appView:$('appView'),loginBtn:$('loginBtn'),logoutBtn:$('logoutBtn'),loginMessage:$('loginMessage'),userEmail:$('userEmail'),headerTitle:$('headerTitle'),searchInput:$('searchInput'),categoryFilter:$('categoryFilter'),availabilityFilter:$('availabilityFilter'),emptyCatalog:$('emptyCatalog'),productGrid:$('productGrid'),formTitle:$('formTitle'),editingId:$('editingId'),productName:$('productName'),price:$('price'),productDate:$('productDate'),category:$('category'),description:$('description'),available:$('available'),featured:$('featured'),photoInput:$('photoInput'),photoPreview:$('photoPreview'),saveProductBtn:$('saveProductBtn'),cancelEditBtn:$('cancelEditBtn'),productMessage:$('productMessage'),manageSearch:$('manageSearch'),productList:$('productList'),shopName:$('shopName'),subtitle:$('subtitle'),saveSettingsBtn:$('saveSettingsBtn'),settingsMessage:$('settingsMessage')};
let products=[],photoData='',settings={shopName:'MSFK Productcatalogus',subtitle:'Bekijk onze producten.'};
const msg=(el,t,e=false)=>{el.textContent=t;el.style.color=e?'#b91c1c':'#15803d'};const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function compressImage(file){const dataUrl=await new Promise((ok,no)=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.onerror=no;fr.readAsDataURL(file)});const image=await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=no;i.src=dataUrl});const max=700,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.68)}
function resetForm(){r.editingId.value='';r.productName.value='';r.price.value='';r.productDate.value='';r.category.value='';r.description.value='';r.available.checked=true;r.featured.checked=false;r.photoInput.value='';r.photoPreview.src='';r.photoPreview.classList.add('hidden');photoData='';r.formTitle.textContent='Nieuw product';r.cancelEditBtn.classList.add('hidden')}
function rebuildCategories(){const current=r.categoryFilter.value,cats=[...new Set(products.map(p=>p.category||'Overig'))].sort();r.categoryFilter.innerHTML='<option value="all">Alle categorieën</option>'+cats.map(c=>`<option value="${safe(c)}">${safe(c)}</option>`).join('');if(cats.includes(current))r.categoryFilter.value=current}
function renderCatalog(){const q=r.searchInput.value.toLowerCase(),cat=r.categoryFilter.value,av=r.availabilityFilter.value,visible=products.filter(p=>{const t=`${p.name||''} ${p.category||''} ${p.description||''}`.toLowerCase();return(!q||t.includes(q))&&(cat==='all'||(p.category||'Overig')===cat)&&(av==='all'||(av==='available'?p.available!==false:p.available===false))}).sort((a,b)=>(Number(!!b.featured)-Number(!!a.featured))||String(a.name||'').localeCompare(String(b.name||''),'nl'));r.productGrid.innerHTML='';r.emptyCatalog.classList.toggle('hidden',visible.length>0);for(const p of visible){const c=document.createElement('article');c.className='card';c.innerHTML=`<div class="photo-wrap">${p.photoData?`<img src="${p.photoData}" alt="${safe(p.name)}">`:'<div class="placeholder">Geen foto</div>'}<span class="badge">${p.available===false?'Uitverkocht':'Beschikbaar'}</span></div><div class="card-body"><div class="category">${safe(p.category||'Overig')}</div><h2>${safe(p.name||'Naamloos product')}</h2><div class="meta">${safe(p.description||'')}${p.productDate?`<br>Datum: ${safe(p.productDate)}`:''}</div><div class="price">CG ${Number(p.price||0).toFixed(2)}</div></div>`;r.productGrid.appendChild(c)}}
function renderList(){const q=r.manageSearch.value.toLowerCase(),visible=products.filter(p=>`${p.name||''} ${p.category||''}`.toLowerCase().includes(q)).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'nl'));r.productList.innerHTML=visible.length?'':'<div class="meta">Nog geen producten.</div>';for(const p of visible){const row=document.createElement('div');row.className='product-row';row.innerHTML=`${p.photoData?`<img src="${p.photoData}" alt="">`:'<div class="row-placeholder">Geen foto</div>'}<div><h3>${safe(p.name)}</h3><div class="meta">CG ${Number(p.price||0).toFixed(2)} · ${safe(p.category||'Overig')}<br>${p.productDate?`Datum: ${safe(p.productDate)} · `:''}${p.available===false?'Uitverkocht':'Beschikbaar'}</div></div><div class="actions"><button class="btn light" data-edit="${p.id}">Bewerken</button><button class="btn light" data-delete="${p.id}">Verwijderen</button></div>`;r.productList.appendChild(row)}r.productList.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));r.productList.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Product verwijderen?'))await deleteDoc(doc(db,'catalogProducts',b.dataset.delete))})}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;r.editingId.value=id;r.productName.value=p.name||'';r.price.value=p.price??'';r.productDate.value=p.productDate||'';r.category.value=p.category||'';r.description.value=p.description||'';r.available.checked=p.available!==false;r.featured.checked=!!p.featured;photoData=p.photoData||'';if(photoData){r.photoPreview.src=photoData;r.photoPreview.classList.remove('hidden')}r.formTitle.textContent='Product aanpassen';r.cancelEditBtn.classList.remove('hidden');document.querySelector('[data-tab="manage"]').click();scrollTo({top:120,behavior:'smooth'})}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
r.loginBtn.onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){if(e.code==='auth/popup-blocked')await signInWithRedirect(auth,provider);else msg(r.loginMessage,'Inloggen mislukt: '+e.message,true)}};r.logoutBtn.onclick=()=>signOut(auth);r.photoInput.onchange=async()=>{const f=r.photoInput.files?.[0];if(!f)return;try{photoData=await compressImage(f);r.photoPreview.src=photoData;r.photoPreview.classList.remove('hidden');msg(r.productMessage,'Foto klaar.')}catch(e){msg(r.productMessage,'Foto kon niet worden verwerkt.',true)}};
r.saveProductBtn.onclick=async()=>{const name=r.productName.value.trim(),price=Number(r.price.value);if(!name)return msg(r.productMessage,'Vul productnaam in.',true);if(!Number.isFinite(price))return msg(r.productMessage,'Vul een geldige prijs in.',true);const data={name,price,productDate:r.productDate.value,category:r.category.value.trim()||'Overig',description:r.description.value.trim(),available:r.available.checked,featured:r.featured.checked,photoData,updatedAt:serverTimestamp()};try{if(r.editingId.value)await setDoc(doc(db,'catalogProducts',r.editingId.value),data,{merge:true});else await addDoc(collection(db,'catalogProducts'),{...data,createdAt:serverTimestamp()});msg(r.productMessage,'Product opgeslagen.');resetForm()}catch(e){msg(r.productMessage,'Opslaan mislukt: '+e.message,true)}};r.cancelEditBtn.onclick=resetForm;
r.saveSettingsBtn.onclick=async()=>{try{await setDoc(doc(db,'publicSettings','catalog'),{shopName:r.shopName.value.trim()||'MSFK Productcatalogus',subtitle:r.subtitle.value.trim(),updatedAt:serverTimestamp()},{merge:true});msg(r.settingsMessage,'Instellingen opgeslagen.')}catch(e){msg(r.settingsMessage,e.message,true)}};r.searchInput.oninput=renderCatalog;r.categoryFilter.onchange=renderCatalog;r.availabilityFilter.onchange=renderCatalog;r.manageSearch.oninput=renderList;getRedirectResult(auth).catch(e=>msg(r.loginMessage,e.message,true));
onAuthStateChanged(auth,user=>{r.loading.classList.add('hidden');if(!user){r.loginView.classList.remove('hidden');r.appView.classList.add('hidden');return}if((user.email||'').toLowerCase()!==OWNER_EMAIL){signOut(auth);r.loginView.classList.remove('hidden');msg(r.loginMessage,'Dit account heeft geen toegang.',true);return}r.loginView.classList.add('hidden');r.appView.classList.remove('hidden');r.userEmail.textContent=user.email;onSnapshot(doc(db,'publicSettings','catalog'),s=>{if(s.exists())settings={...settings,...s.data()};r.headerTitle.textContent=settings.shopName;r.shopName.value=settings.shopName;r.subtitle.value=settings.subtitle;document.title=settings.shopName},e=>msg(r.settingsMessage,e.message,true));onSnapshot(collection(db,'catalogProducts'),s=>{products=s.docs.map(d=>({id:d.id,...d.data()}));rebuildCategories();renderCatalog();renderList()},e=>msg(r.productMessage,e.message,true))});
